name: CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env: 
  job1: "abc"
  job2: "def"
  job3: "xyz"
  jobs: '"abc","def","xyz"'
  jobsJSON: "{[abc,def,xyz]}"

jobs:
  prebuild:
    runs-on: ubuntu-latest
    steps: 
      run: ${{ fromJson($jobsJSON) }}.Split(",")
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        #node: [$job1, $job2, $job3]
        node: [$(fromJson($jobsJSON)]
    steps:
      - name: Run a one-line script
        run: echo "Hello, world ${{ matrix.node }} !"
