name: CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env: 
  job1: "abc"
  job2: "def"
  job3: "xyz"
  jobs: '"abc","def","xyz"'
  jobsJSON: "{[abc,def,xyz]}"

jobs:
  prepareArray:
    runs-on: ubuntu-latest
    outputs:
      myJson: ${{ steps.generate-matrix.outputs.services }}
    steps:
      - uses: actions/checkout@v2
      #- run: echo ${{ fromJson(./data.json) }}
      - id: set_var
        run: |
          ls 
          # reference: https://stackoverflow.com/questions/61919141/read-json-file-in-github-actions/61919791
          content=`cat data.json`
          # the following lines are only required for multi line json
          content="${content//'%'/'%25'}"
          content="${content//$'\n'/'%0A'}"
          content="${content//$'\r'/'%0D'}"
          # end of optional handling for multi line json
          echo "::set-output name=myJson::$content"
      - run: |
          echo "${{fromJson(steps.set_var.outputs.myJson)}}"
          echo "${{fromJson(prepareArray.outputs.myJson)}}"
  prepareCheck:
    runs-on: ubuntu-latest
    needs: prepareArray
    steps: 
      - run: echo "${{ toJSON(needs.prepareArray.outputs.myJson) }}" 
  build:
    runs-on: ubuntu-latest
    needs: [prepareArray, prepareCheck]
    strategy:
      matrix:
        #node: [$job1, $job2, $job3]
        node: [$fromJson(needs.prepareArray.outputs.myJson)]
    steps:
      - name: Run a one-line script
        run: echo "Hello, world ${{ matrix.node }} !"
