# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env: 
  job1: "abc"
  job2: "def"
  job3: "xyz"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  prebuild:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, world ${{ env.job1 }}, ${{ env.job2 }}, ${{ env.job3 }}!
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        type: ["${{ env.job1 }}", "${{ env.job2 }}", "${{ env.job3 }}"]
    steps:
      - name: Run a one-line script
        run: echo Hello, world ${{ matrix.type }}!
